# Generated by Django 4.1.3 on 2023-01-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_endereco_cliente_endereco"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dependente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=12)),
                (
                    "titular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cliente"
                    ),
                ),
            ],
        ),
    ]
