# Generated by Django 4.1.3 on 2023-01-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_dependente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "clientes",
                    models.ManyToManyField(
                        related_name="atendente_cliente", to="app.cliente"
                    ),
                ),
            ],
        ),
    ]
