# Generated by Django 4.1.3 on 2023-01-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_atendente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependente",
            name="titular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependente",
                to="app.cliente",
            ),
        ),
        migrations.AlterModelTable(
            name="atendente",
            table="app_funcionario",
        ),
    ]
